FROM python:3.13-trixie

WORKDIR /app

# Install uv / no venv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV UV_SYSTEM_PYTHON=1
ENV PATH="/root/.local/bin:/app/.local/bin:${PATH}"

# Java for Tika
RUN apt install -y openjdk-25-jdk

# Cache the requirements if possible
COPY src_ingest/src/requirements.txt /app/.
RUN uv pip install -r requirements.txt

# Copy the APP
COPY src_ingest/* /app/

ENTRYPOINT ["python3","ingest.py"]

