FROM python:3.13-trixie

WORKDIR /app

# Install uv / no venv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV UV_SYSTEM_PYTHON=1
ENV PATH="/root/.local/bin:/app/.local/bin:${PATH}"

# Cache the requirements if possible
COPY src_langgraph/src/requirements.txt /app/.
RUN uv pip install -r requirements.txt

# Copy the APP
COPY src_langgraph/* /app/

ENTRYPOINT ["langgraph", "dev", "--host", "0.0.0.0"]

