apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-dep
  labels:
      app: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
      - name: app
        image: ##DOCKER_PREFIX##/##TF_VAR_prefix##-##APP_NAME##
        imagePullPolicy: Always
        ports:
        - containerPort: 2025
        envFrom:
          - configMapRef:
              name: tf-env-configmap        
      imagePullSecrets:
      - name: ocirsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-service
spec:
  selector:
    app: mcp-server
  ports:
  - name: http-service-port
    protocol: TCP
    port: 2025
    targetPort: 2025
---